{
 "title": "Custom Exporter",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "city",
    "query": {
     "query": "label_values(weather_temp_celsius,city)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "кол городов где 0 с",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(weather_temp_celsius < 0)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "скорость изменения влажности ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(weather_humidity_percent[5m])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "сред темп по городам ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(weather_temp_celsius)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "max temp ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "weather_temp_max_celsius", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "last update timestamp",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "weather_last_update_timestamp", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "время восхода и захода (unix timestamp)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "weather_sunrise_timestamp", "legendFormat": "__auto" },
    { "expr": "weather_sunset_timestamp", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "видимость в метрах",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    { "expr": "weather_visibility_meters", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "направление ветра",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "weather_wind_deg", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "wind speed m/s",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "weather_wind_speed", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "давление в hpa",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "targets": [
    { "expr": "weather_pressure_hpa", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "проц влажности и облачность ",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "targets": [
    { "expr": "weather_humidity_percent", "legendFormat": "__auto" },
    { "expr": "weather_cloudiness_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "темп по ощущениям ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "weather_feels_like_celsius", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "temp right now ",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weather_temp_celsius{city=\"$city\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}