{
 "title": "Database Exporter",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "query0",
    "query": {
     "query": "label_values(pg_database_size_bytes,datname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "размер бд в байтах",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_database_size_bytes{datname=\"olist_db\"} / 1024 / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of scheduled checkpoints that have been performed",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_stat_bgwriter_checkpoints_timed_total ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "кол. таблиц, строк и + удаленные строки",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(pg_stat_user_tables_n_live_tup{datname=\"$query0\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(pg_stat_user_tables_n_live_tup{datname=\"$query0\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(pg_stat_user_tables_n_tup_del{datname=\"$query0\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "привилегия пользователя ",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "pg_roles_connection_limit", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "количество пользователей ",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(pg_roles_connection_limit)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "скорость запросов ",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "pg_stat_database_xact_commit{datname=\"olist_db\"}\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "запись блоков ",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(pg_stat_database_blks_hit{datname=\"olist_db\"}[5m])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "время работы в часах",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "(time() - process_start_time_seconds) / 3600\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "размер бд гигабайт",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_database_size_bytes{datname=\"olist_db\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "активные подключения ",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_locks_count{datname=\"olist_db\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}