{
 "title": "Node Exporter",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "disk",
    "query": {
     "query": "label_values(node_disk_read_bytes_total,device)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "нынешний проц батареи ",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_power_supply_current_capacity{power_supply=\"InternalBattery-0\"}\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "скорость исходящего графика",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{device=\"en0\"}[5m])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "скорость входящего трафика ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device=\"en0\"}[5m])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "скорость записи данных байт/сек",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(node_disk_written_bytes_total{device=\"disk0\"}[5m])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "скорость чтения байт/сек",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{device=\"$disk\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "свободное место на диске ",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{fstype!~\"tmpfs|autofs\"} / 1024 / 1024 / 1024\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "сколько процентов памяти используется ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (node_memory_total_bytes - (node_memory_free_bytes + node_memory_inactive_bytes + node_memory_purgeable_bytes)) / node_memory_total_bytes\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "общая, использованная и свободная память ",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "node_memory_total_bytes / 1024 / 1024 / 1024\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "(node_memory_active_bytes + node_memory_wired_bytes + node_memory_compressed_bytes) / 1024 / 1024 / 1024\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "(node_memory_free_bytes + node_memory_inactive_bytes + node_memory_purgeable_bytes) / 1024 / 1024 / 1024\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Load average (1, 5, 15 минут)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    { "expr": "node_load1\n", "legendFormat": "__auto" },
    { "expr": "node_load5\n", "legendFormat": "__auto" },
    { "expr": "node_load15\n", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "cpu usage в процентах",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "100 * (1 - avg by(cpu)(rate(node_cpu_seconds_total{mode=\"idle\"}[1m])))\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}